//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faune_Interaction_Sujet
    {
        public int sujet_id { get; set; }
        public int faune_id { get; set; }
    }
}
