//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faune
    {
        public int faune_id { get; set; }
        public string embranchement { get; set; }
        public string classe { get; set; }
        public string ordre { get; set; }
        public string sous_ordre { get; set; }
        public string famille { get; set; }
        public string sous_famille { get; set; }
        public string tribu { get; set; }
        public string genre { get; set; }
        public string nom_commun { get; set; }
    }
}
