//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meteo
    {
        public int meteo_id { get; set; }
        public int potager_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<float> temperature { get; set; }
        public Nullable<float> pluviometrie { get; set; }
        public Nullable<float> vent { get; set; }
        public Nullable<float> humidite { get; set; }
    
        public virtual Potager Potager { get; set; }
    }
}
