//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PotagerEntities : DbContext
    {
        public PotagerEntities()
            : base("name=PotagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faune> Faune { get; set; }
        public virtual DbSet<Faune_Dans_Potager> Faune_Dans_Potager { get; set; }
        public virtual DbSet<Faune_Interaction_Sujet> Faune_Interaction_Sujet { get; set; }
        public virtual DbSet<Flore_Dans_Potager> Flore_Dans_Potager { get; set; }
        public virtual DbSet<Flore_Interaction_Sujet> Flore_Interaction_Sujet { get; set; }
        public virtual DbSet<Graine> Graine { get; set; }
        public virtual DbSet<Meteo> Meteo { get; set; }
        public virtual DbSet<Plante> Plante { get; set; }
        public virtual DbSet<Potager> Potager { get; set; }
        public virtual DbSet<Recolte> Recolte { get; set; }
        public virtual DbSet<Sujet> Sujet { get; set; }
        public virtual DbSet<Sujet_Entretien> Sujet_Entretien { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
        public virtual DbSet<Zone_Modification> Zone_Modification { get; set; }
    }
}
