//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plante
    {
        public int plante_id { get; set; }
        public string nom_commun { get; set; }
        public string regne { get; set; }
        public string sous_regne { get; set; }
        public string division { get; set; }
        public string classe { get; set; }
        public string sous_classe { get; set; }
        public string ordre { get; set; }
        public string famille { get; set; }
        public string genre { get; set; }
        public string espece { get; set; }
        public string variete { get; set; }
    
        public virtual Graine Graine { get; set; }
        public virtual Sujet Sujet { get; set; }
    }
}
