//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        public int terrain_id { get; set; }
        public string ville { get; set; }
        public string type_sol { get; set; }
        public string structures { get; set; }
    
        public virtual Meteo Meteo { get; set; }
    }
}
