//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone_Modification
    {
        public int zone_modification_id { get; set; }
        public int zone_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string modification { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
